name: Build Test

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  test-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            ~/AppData/Local/electron/Cache
            ~/Library/Caches/electron
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 0
          ELECTRON_CACHE: ${{ runner.temp }}/electron-cache

      - name: Run Vite build
        run: npm run build

      - name: Test Electron packaging for Windows
        run: npm run build:win:simple
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify build artifacts exist
        shell: bash
        run: |
          if [ -d "dist" ]; then
            echo "✅ Build artifacts created successfully"
            ls -la dist/
          else
            echo "❌ Build artifacts not found"
            exit 1
          fi